---
title: "Clausal Form Exercises"
header-includes:
    - \usepackage{xcolor}
    - \usepackage{fitch}
---

# Exercise 5.1

For each of the following sentences, say which set of clauses is the correct clausal form.

1. $p \land q \Rightarrow r \lor s$
    . $\{p, q, r, s\}$  
    . $\{\lnot p, \lnot q, r, s\}$ $\color{green} \surd$  
    . $\{\lnot p, \lnot q, r\}, \{\lnot p, \lnot q, s\}$  
    . $\{\lnot p, r, s\}, \{\lnot q, r, s\}$  
    . $\{\lnot p\}, \{\lnot q\}, \{r\}, \{s\}$  

2. $p \lor q \Rightarrow r \lor s$
    . $\{p, q, r, s\}$  
    . $\{\lnot p, \lnot q, r, s\}$  
    . $\{\lnot p, \lnot q, r\}, \{\lnot p, \lnot q, s\}$  
    . $\{\lnot p, r, s\}, \{\lnot q, r, s\}$ $\color{green} \surd$  
    . $\{\lnot p\}, \{\lnot q\}, \{r\}, \{s\}$  

3. $\lnot (p \lor q \lor r)$  
    . $\{\lnot p, \lnot q, \lnot r\}$  
    . $\{\lnot p\}, \{\lnot q\}, \{\lnot r\}$ $\color{green} \surd$   

4. $\lnot (p \land q \land r)$  
    . $\{\lnot p, \lnot q, \lnot r\}$ $\color{green} \surd$   
    . $\{\lnot p\}, \{\lnot q\}, \{\lnot r\}$  

5. $p \land q \Leftrightarrow r$  
    . $\{p, q\}, \{r\}$  
    . $\{\lnot p, \lnot q\}, \{r\}$  
    . $\{\lnot p, \lnot q, r\}, \{\lnot r, p\}, \{\lnot r, q\}$ $\color{green} \surd$   
    . $\{\lnot p, r\}, \{\lnot q, r\}, \{p, q, \lnot r\}$  
    . $\{p\}, \{q\}, \{r\}$  

# Exercise 5.2


In each of the following questions, say which of the answers best characterizes the result of applying resolution to the clauses shown.

1. $\{p, q, \lnot r\}$ and $\{r, s\}$  
    . $\{p, q, s\}$  $\color{green} \surd$     
    . $\{p, q, r, s\}$  
    . $\{p, q, \lnot r, s\}$  
    . There are no resolvents.  
  
2. $\{p, q, r\}$ and $\{r, \lnot s, \lnot t\}$  
    . $\{p, q, r, \lnot s, \lnot t\}$  
    . $\{p, q, \lnot s, \lnot t\}$  
    . There are no resolvents. $\color{green} \surd$     
  
3. $\{q, \lnot q\}$ and $\{q, \lnot q\}$  
    . $\{q, \lnot q\}$ $\color{green} \surd$     
    . $\{q\}$  
    . $\{\lnot q\}$  
    . $\{\}$  
    . There are no resolvents.  
  
4. $\{\lnot p, q, r\}$ and $\{p, \lnot q, \lnot r\}$  
    . $\{\lnot p, q, r, p, \lnot q, \lnot r\}$  
    . $\{q, r, \lnot q, \lnot r\}$, $\{\lnot p, r, p, \lnot r\}$, $\{\lnot p, q, p, \lnot q\}$ $\color{green} \surd$     
    . $\{p, \lnot p\}$, $\{q, \lnot q\}$, $\{r, \lnot r\}$  
    . $\{\}$  
    . There are no resolvents.  

# Exercise 5.3

Use Propositional Resolution to show that the clauses $\{p, q\}$, $\{\lnot p, r\}$, $\{\lnot p, \lnot r\}$, $\{p, \lnot q\}$ are not simultaneously satisfiable.
$$
\begin{fitch}
\fa \{p,q\} & Premise\\
\fa \{\lnot p,r\} & Premise\\
\fa \{\lnot p,\lnot r\} & Premise\\
\fj \{p,\lnot q\} & Premise\\
\fa \{p\} & Resolution (1,4)\\
\fa \{\lnot p\} & Resolution (2,3)\\
\fa \{\} & Resolution (5,6)\\
\end{fitch}
$$

# Exercise 5.4

Given the premises $(p \Rightarrow q)$ and $(r \Rightarrow s)$,use Propositional Resolution to prove the conclusion $(p \lor r \Rightarrow q \lor s)$.

Note: I already converted the premise to clausal form, I'll add the clausal form process later.

$$
\begin{fitch}
\fa \{\lnot p,q\} & Premise\\
\fa \{\lnot r,s\} & Premise\\
\fa \{p,r\} & Premise\\
\fa \{\lnot q\} & Premise\\
\fj \{\lnot s\} & Premise\\
\fa \{\lnot r\} & Resolution (2,5)\\
\fa \{\lnot p\} & Resolution (1,4)\\
\fa \{p\} & Resolution (3,6)\\
\fa \{\} & Resolution (8,7)\\
\end{fitch}
$$
