---
title: "Proofs exercises"
header-includes:
    - \usepackage{fitch}
---

# Exercise 4.1

Given $p$ and $q$ and $p \land q \Rightarrow r$, use the Fitch system to prove $r$.
$$
\begin{fitch}
\fa p & Premise\\ 
\fa q & Presmise\\
\fj p \land q \Rightarrow r & Presmise\\
\fa p \land q & And Introduction (1,2) \\
\fa r & Implication Elimination (3,4)
\end{fitch}
$$

# Exercise 4.2

Given $p \land q$, use the Fitch system to prove $q \lor r$

$$
\begin{fitch}
\fj p \land q & Premise \\
\fa q & And Elimination (1) \\
\fa q \lor r & Or Introduction (2)
\end{fitch}
$$

# Exercise 4.3

Given $p \Rightarrow q$ and $q \Leftrightarrow r$, use the Fitch system to prove $p \Rightarrow r$.

$$
\begin{fitch}
\fa p \Rightarrow q & Premise \\
\fj q \Leftrightarrow r & Premise \\
\fa \fa p & Assumption \\
\fa \fa q & Implication Elimination (1,3) \\
\fa \fa r & Implication Elimination (5,4) \\
\fa p \Rightarrow r & Implication Introduction (3,6)
\end{fitch}
$$

# Exercise 4.4

Given $p \Rightarrow q$ and $m \Rightarrow p \land q$, use the Fitch System to prove $m \Rightarrow q$.

$$
\begin{fitch}
\fa p \Rightarrow q & Premise\\
\fj m \Rightarrow p \lor q & Premise\\
\fa \fa q & Assumption\\
\fa q \Rightarrow q & Implication Introduction (3,3)\\
\fa \fa m & Assumption\\
\fa \fa p \lor q & Implication Elimination (2,5)\\
\fa \fa q & Or Elimination (6,1,4)\\
\fa m \Rightarrow q & Implication Introduction (5,7)\\
\end{fitch}
$$

# Exercise 4.5


Given $p \Rightarrow (q \Rightarrow r)$, use the Fitch System to prove $(p \Rightarrow q) \Rightarrow (p \Rightarrow r)$

$$
\begin{fitch}
\fj p \Rightarrow (q \Rightarrow r) & Premise\\
\fa \fa p \Rightarrow q & Assumption\\
\fa \fa \fa p & Assumption\\
\fa \fa \fa q \Rightarrow r & Implication Elimination
 (1,3)\\
\fa \fa \fa q & Implication Elimination (2,3)\\
\fa \fa \fa r & Implication Elimination (4,5)\\
\fa \fa p \Rightarrow r & Implication Introduction (3
,6)\\
\fa (p \Rightarrow q) \Rightarrow (p \Rightarrow r) &
 Implication Introduction (2,7)\\
\end{fitch}
$$


# Exercise 4.6

Use the fitch System to prove $p \Rightarrow (q \Rightarrow p)$

$$
\begin{fitch}
\fa \fa p & Assumption\\
\fa \fa \fa q & Assumption\\
\fa \fa \fa p & Reiteration (1)\\
\fa \fa q \Rightarrow p & Implication Introduction (2,3)\\
\fa p \Rightarrow (q \Rightarrow p) & Implication Introduction (1,4)\\
\end{fitch}
$$

# Exercise 4.7

Use the Fitch System to prove $(p \Rightarrow (q \Rightarrow r)) \Rightarrow ((p \Rightarrow q) \Rightarrow (p \Rightarrow r))$

$$
\begin{fitch}
\fa \fa p \Rightarrow (q \Rightarrow r) & Assumption\\
\fa \fa \fa p \Rightarrow q & Assumption\\
\fa \fa \fa \fa p & Assumption\\
\fa \fa \fa \fa q & Implication Elimination (2,3)\\
\fa \fa \fa \fa q \Rightarrow r & Implication Elimination (1,3)\\
\fa \fa \fa \fa r & Implication Elimination (5,4)\\
\fa \fa \fa p \Rightarrow r & Implication Introduction (3,6)\\
\fa \fa (p \Rightarrow q) \Rightarrow (p \Rightarrow r) & Implication Introduction (2,7)\\
\fa (p \Rightarrow (q \Rightarrow r)) \Rightarrow ((p \Rightarrow q) \Rightarrow (p \Rightarrow r)) & Implication Introduction (1,8)\\
\end{fitch}
$$

# Exercise 4.8

Use the Fitch System to prove $(\lnot p \Rightarrow q) \Rightarrow ((\lnot p \Rightarrow \lnot q) \Rightarrow p)$


$$
\begin{fitch}
\fa \fa \lnot p \Rightarrow q & Assumption\\
\fa \fa \fa \lnot p \Rightarrow \lnot q & Assumption\\
\fa \fa \fa \lnot \lnot p & Negation Introduction (1,2)\\
\fa \fa \fa p & Negation Elimination (3)\\
\fa \fa (\lnot p \Rightarrow \lnot q) \Rightarrow p & Implication Introduction (2,4)\\
\fa (\lnot p \Rightarrow q) \Rightarrow ((\lnot p \Rightarrow \lnot q) \Rightarrow p) & Implication Introduction (1,5)\\
\end{fitch}
$$

# Exercise 4.9

Given $p$, use the Fitch System to prove $\lnot \lnot p$

$$
\begin{fitch}
\fj p & Premise\\
\fa \fa \lnot p & Assumption\\
\fa \fa p & Reiteration (1)\\
\fa \lnot p \Rightarrow p & Implication Introduction (2,3)\\
\fa \fa \lnot p & Assumption\\
\fa \lnot p \Rightarrow \lnot p & Implication Introduction (5,5)\\
\fa \lnot \lnot p & Negation Introduction (4,6)\\
\end{fitch}
$$

# Exercise 4.10

Given $p \Rightarrow q$, use the Fitch System to prove $\lnot q \Rightarrow \lnot p$.

$$
\begin{fitch}
\fj p \Rightarrow q & Premise\\
\fa \fa \lnot q & Assumption\\
\fa \fa \fa p & Assumption\\
\fa \fa \fa q & Implication Elimination (1,3)\\
\fa \fa p \Rightarrow q & Implication Introduction (3,4)\\
\fa \fa \fa p & Assumption\\
\fa \fa \fa \lnot q & Reiteration (2)\\
\fa \fa p \Rightarrow \lnot q & Implication Introduction (6,7)\\
\fa \fa \lnot p & Negation Introduction (5,8)\\
\fa \lnot q \Rightarrow \lnot p & Implication Introduction (2,9)\\
\end{fitch}
$$

# Exercise 4.11

Given $p \Rightarrow q$, use the Fitch System to prove $\lnot p \lor q$

$$
\begin{fitch}
\fj p \Rightarrow q & Premise\\
\fa \fa \lnot (\lnot p \lor q) & Assumption\\
\fa \fa \fa \lnot p & Assumption\\
\fa \fa \fa \lnot p \lor q & Or Introduction (3)\\
\fa \fa \lnot p \Rightarrow \lnot p \lor q & Implication Introduction (3,4)\\
\fa \fa \fa \lnot p & Assumption\\
\fa \fa \fa \lnot (\lnot p \lor q) & Reiteration (2)\\
\fa \fa \lnot p \Rightarrow \lnot (\lnot p \lor q) & Implication Introduction (6,7)\\
\fa \fa \lnot \lnot p & Negation Introduction (5,8)\\
\fa \fa p & Negation Elimination (9)\\
\fa \lnot (\lnot p \lor q) \Rightarrow p & Implication Introduction (2,10)\\
\fa \fa \lnot (\lnot p \lor q) & Assumption\\
\fa \lnot (\lnot p \lor q) \Rightarrow \lnot (\lnot p \lor q) & Implication Introduction (12,12)\\
\fa \fa \lnot (\lnot p \lor q) & Assumption\\
\fa \fa p & Implication Elimination (11,14)\\
\fa \fa q & Implication Elimination (1,15)\\
\fa \fa \lnot p \lor q & Or Introduction (16)\\
\fa \lnot (\lnot p \lor q) \Rightarrow \lnot p \lor q & Implication Introduction (14,17)\\
\fa \lnot \lnot (\lnot p \lor q) & Negation Introduction (18,13)\\
\fa \lnot p \lor q & Negation Elimination (19)\\
\end{fitch}
$$
